### ISSUE TITLE
Add https support.

### ISSUE THREAD

**Issue by mmerickel** [rfk/m2wsgi#3]
It looks like the WSGI environ is hard-coded with port 80, and http. I'm only starting to play with mongrel but it looks like it has at least some support for notifying a handler that it's being accessed via https.

**Comment by rfk** [comment]
Thanks for reaching out. Unfortunately I am no longer actively maintaining this project, so I'm going to move it into archive mode:

  https://rfk.id.au/blog/entry/archiving-open-source-projects/
